### ISSUE TITLE
Flaky /dev/hidraw causing haptics worker panic

### ISSUE THREAD

**Issue by DottieUnderwood** [daniel5151/surface-dial-linux#1]
Greetings,

excellent work Daniel.

The software works fine with Fedora 33. However when the BT connection to the dial device is lost the user-daemon crashes. After a restart it continues working.

> Nov 13 13:10:50 X systemd[2429]: Started Surface Dial Daemon.
> Nov 13 13:10:50 X surface-dial-daemon[13464]: Started
> Nov 13 13:10:50 X surface-dial-daemon[13464]: haptics worker is waiting...
> Nov 13 13:10:50 X surface-dial-daemon[13464]: haptics worker is ready
> Nov 13 13:10:50 X surface-dial-daemon[13464]: Dial Connected
> Nov 13 13:10:50 X surface-dial-daemon[13464]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MissingDial', src/dial_device/mod.rs:72:30
> Nov 13 13:10:50 X surface-dial-daemon[13464]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Nov 13 13:18:50 X surface-dial-daemon[13464]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/dial_device/events.rs:93:18
> Nov 13 13:18:50 X surface-dial-daemon[13464]: thread '<unnamed>' panicked at 'Could not recv event', src/dial_device/mod.rs:131:24
> Nov 13 13:18:50 X surface-dial-daemon[13464]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/controller/controls/media_with_volume.rs:17:22

**Comment by daniel5151** [comment]
Hmm, seems like my assumption that `/dev/hidrawX` would be ready before `/dev/input/eventX` wasn't correct.

I've pushed up a tentative fix to the `hidraw-poll` branch, could you try it out and let me know if it helps?

If it doesn't work, please re-run the daemon with the `RUST_BACKTRACE=1` environment variable set.

**Comment by DottieUnderwood** [comment]
Did not work unfortunately. Here is the backtrace (from the hidraw-poll branch).

> $ RUST_BACKTRACE=1 /usr/local/bin/surface-dial-daemon                                                                                         
> Started
> haptics worker is waiting...
> haptics worker is ready
> Dial Connected
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MissingDial', src/dial_device/mod.rs:72:30
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_none_failed
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> --- It worked until here
> --- BATTERY REMOVED FROM DEVICE
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/dial_device/events.rs:93:18
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_none_failed
>    3: surface_dial_daemon::dial_device::events::EventsWorker::event_loop
>    4: surface_dial_daemon::dial_device::events::EventsWorker::run
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'Could not recv event', src/dial_device/mod.rs:131:24
> stack backtrace:
>    0: std::panicking::begin_panic
>    1: surface_dial_daemon::dial_device::DialDevice::next_event
>    2: surface_dial_daemon::controller::DialController::run
>    3: surface_dial_daemon::controller_main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/controller/controls/media_with_volume.rs:17:22
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_none_failed
>    3: surface_dial_daemon::controller::controls::media_with_volume::double_click_worker
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by daniel5151** [comment]
Are you sure that's from the right branch? `thread '' panicked at 'called Result::unwrap() on an Err value: MissingDial', src/dial_device/mod.rs:72:30` shouldn't be possible, as I removed the `MissingDial` error from the `DialHapticsWorker`.

**Comment by DottieUnderwood** [comment]
Accidentally build the wrong branch. Here is the real backtrace.

> $ RUST_BACKTRACE=1 /usr/local/bin/surface-dial-daemon                                                                                     1  
> Started
> haptics worker is waiting...
> haptics worker is ready
> Dial Connected
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: HidError(OpenHidDeviceError)', src/dial_device/mod.rs:72:30
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::result::unwrap_failed
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> --- It worked until here
> --- BATTERY REMOVED FROM DEVICE
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/dial_device/events.rs:93:18
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::result::unwrap_failed
>    3: surface_dial_daemon::dial_device::events::EventsWorker::event_loop
>    4: surface_dial_daemon::dial_device::events::EventsWorker::run
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'Could not recv event', src/dial_device/mod.rs:131:24
> stack backtrace:
>    0: std::panicking::begin_panic
>    1: surface_dial_daemon::dial_device::DialDevice::next_event
>    2: surface_dial_daemon::controller::DialController::run
>    3: surface_dial_daemon::controller_main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/controller/controls/media_with_volume.rs:17:22
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::result::unwrap_failed
>    3: surface_dial_daemon::controller::controls::media_with_volume::double_click_worker
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by daniel5151** [comment]
Huh. That's very spooky...

Can you do me a favor and play around with the time delay on `src/dial_device/haptics.rs:71` and see if it helps to bump it up? Try setting it to 500ms and 1000ms and seeing if it works.

Additionally, could you check if the `/dev/hidrawX` device shows up when the device re-connects? This is bit finicky, but if you run `ls -al /dev/hidraw*` before connecting the dial, re-run it after connecting the dial, and then `cat /dev/hidrawX | xxd` (where X is the device that was just added), you should see a bunch of output after interacting with the dial.

**Comment by DottieUnderwood** [comment]
The device /dev/hidraw8 comes and goes as the device is connected and stuff is output when using the dial.

 I tried delays up to 10000 but the error stays the same.

**Comment by daniel5151** [comment]
Uh oh. That's very weird.

Unfortunately, I don't know too much about how `/dev/hidraw` works under the hood, and since I can't repo this issue locally, I'm not sure how much more help I can be :disappointed:

As a workaround, you could try following the old installation instruction from https://github.com/daniel5151/surface-dial-linux/tree/559a28c2d7c8f0849d88c83e01ab08df90f5bb04#installation. These instructions were written before the daemon could gracefully handle disconnects/reconnects, and would simply crash when the dial disconnected. In a nutshell, it sets up the systemd service to restart whenever the device is connected. It's pretty janky though, hence why I re-wrote the daemon.

I'd also recommend looking in to why the `hidraw` device keeps appearing/disappearing, since I don't think that should be happening.

* * *

I'm going to leave this issue open and mark it as can't repo. 

The fix would probably require rewriting the `DialHapticsWorker` to include it's own `udev` loop that waits for the `hidraw` device to be available (similar to the one in `src/dial_device/events.rs:103 - EventsWorker::run()`), though I'm not sure when I'll have time to do that.

**Comment by DottieUnderwood** [comment]
I played around with this a little bit. The systemd-solution looks like it could work, but there is a problem. When the error occurs, the daemon will actually hang and not crash as I said earlier. If the daemon would just quit after the SendError, it could be restarted by systemd. I am to clueless about Rust to maker this change however.

**Comment by daniel5151** [comment]
I pushed up a change to the main branch that causes the program to terminate if the HapticsWorker dies.
Let me know if you were able to get it working.

**Comment by DottieUnderwood** [comment]
It still won't terminate.

> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/dial_device/events.rs:93:18
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_none_failed
>    3: surface_dial_daemon::dial_device::events::EventsWorker::event_loop
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'Could not recv event', src/dial_device/mod.rs:135:24
> stack backtrace:
>    0: std::panicking::begin_panic
>    1: surface_dial_daemon::dial_device::DialDevice::next_event
>    2: surface_dial_daemon::controller_main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/controller/controls/media_with_volume.rs:17:22
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_none_failed
>    3: surface_dial_daemon::controller::controls::media_with_volume::double_click_worker
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

It hangs forever at this point.

> LANG=C git status
> On branch main
> Your branch is up to date with 'origin/main'.
> 
> nothing to commit, working tree clean

**Comment by daniel5151** [comment]
Ah, that's because I'm a dummy and called `panic!` instead of `eprintln!` in my fix. 
I've fixed that, though I did it via a force-push, so you might have to `git reset --hard HEAD^ && git pull`.

**Comment by DottieUnderwood** [comment]
I found the cause of the problems.

The udev-rules `99-uinput.rules` and `99-surface-dial.rules` need to be called `10-uinput.rules` ...

The udev rules must be ordered before 70-...
according to this info https://github.com/OpenCBM/OpenCBM/pull/8

With this change both the version that used first and the current version work.

**Comment by daniel5151** [comment]
Huh, fascinating... great sleuthing!
I guess some distros are more strict about this sort of thing than others. Interesting.

I just pushed up a commit that changes the .rules prefix to `10-`and updates the install instructions accordingly.

Glad we could figure this out!
